version: '3'
services:

  bot:
    build:
      context: .
    restart: on-failure
    volumes:
    - .:/app
    environment:
      # vk settings
      VK_LOGIN:
      VK_PASS:
      VK_WALL_ID:
      # telegram settings
      TARGET_CHANNEL:
      TEST_CHANNEL:
      TG_BOT_TOKEN:
      TG_ME: