version: '3'
services:

  bot:
    build:
      context: .
    depends_on:
      - db
      - redis
    restart: on-failure
    command: bash -c "alembic upgrade head && python -m src"
    env_file:
      - ./.env

  db:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: library/redis:5-alpine
    restart: on-failure
    volumes:
    - redis-data:/data
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  pgdata:
  redis-data: